name: Build and push CentOS7 images to Quay.io registry
on:
  push:
    branches:
      - master
  schedule:
      - cron: '0 1 * * 3'

jobs:
  build-and-push:
    if: github.repository_owner == 'sclorg'
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - dockerfile_path: "2.7"
            dockerfile: "Dockerfile"
            registry_namespace: "centos7"
            quayio_username: "QUAY_IMAGE_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_BUILDER_TOKEN"
            tag: "centos7"
          - dockerfile_path: "3.8"
            dockerfile: "Dockerfile"
            registry_namespace: "centos7"
            quayio_username: "QUAY_IMAGE_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_BUILDER_TOKEN"
            tag: "centos7"
          - dockerfile_path: "3.9"
            dockerfile: "Dockerfile"
            registry_namespace: "centos7"
            quayio_username: "QUAY_IMAGE_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_BUILDER_TOKEN"
            tag: "centos7"
          - dockerfile_path: "3.9-minimal"
            dockerfile: "Dockerfile.rhel8"
            registry_namespace: "sclorg"
            quayio_username: "QUAY_IMAGE_SCLORG_BUILDER_USERNAME"
            quayio_token: "QUAY_IMAGE_SCLORG_BUILDER_TOKEN"
            tag: "el8"
    steps:
      - name: Build and push to quay.io registry
        uses: sclorg/build-and-push-action@v1
        with:
          registry: "quay.io"
          registry_namespace: ${{ matrix.registry_namespace }}
          registry_username: ${{ secrets[matrix.quayio_username] }}
          registry_token: ${{ secrets[matrix.quayio_token] }}
          dockerfile: ${{ matrix.dockerfile }}
          dockerfile_path: ${{ matrix.dockerfile_path }}
          use_distgen: "true"
          tag: ${{ matrix.tag }}
